### ISSUE TITLE
Issue installing the main package in node 14

### ISSUE THREAD

**Issue by navin-moorthy** [richardgill/tailwind-override#1]
*Solution:*

Removing these fields from package.json of the [main package](https://github.com/richardgill/tailwind-override/blob/master/packages/tailwind-override/package.json) would solve the issue- 

```
"engines": {
    "node": ">= 13.4 < 14"
  },
 "engine-strict": true,
```

Hope this is only necessary for CLI version.

**Comment by richardgill** [comment]
That seems sensible @navin-moorthy - do you want to PR that change and I'll merge it.

**Comment by navin-moorthy** [comment]
Yup, I will do the change & raise a PR !!

Thanks 😄

**Comment by navin-moorthy** [comment]
Kindly release a new package version after merging.

Excellent package to override tailwind classes !!
