### ISSUE TITLE
Breaks responsive breakpoint prefixes 

### ISSUE THREAD

**Issue by lukecaan** [richardgill/tailwind-override#22]
When I use overrideTailwindClasses, it's clearing out all of my seperate break-point styles except for the one most to the left.

E.g. when I have a component with classes: `sm:px-4 md:px-6 lg:px-8` .. it ends up only having `lg:px-8` applied. Would be good if it could recognise that the same style with different breakpoint settings can exist side-by-side

**Comment by richardgill** [comment]
Hi @lukecaan, this was a bug. It's fixed in 0.4.0 on npm.

Thanks for reporting :)
