### ISSUE TITLE
Clash between classes for different properties for same feature is resolved incorrectly 

### ISSUE THREAD

**Issue by saurabhgupta050890** [richardgill/tailwind-override#28]
tailwind provide classes for different properties for same feature like text, background, border divide etc. 

This utility considers classes starting from same keyword once.

For example `text-black text-xl text-opacity-2` will return `text-opacity-2` but all three classes are used to apply different properties, `color, font-size and opacity`.

**Comment by richardgill** [comment]
Hi @saurabhgupta050890, thanks for reporting this bug!

I couldn't find any problems with `text-xl` being removed - so please let me know if there is something I'm missing here.

`text-black` and `text-opacity-2` were considered to be clashes, but you are right - they shouldn't!

I've fixed this in #29 and you can grab the latest version of the library is has been published to npm as `0.6.1`. 

Thanks!

**Comment by saurabhgupta050890** [comment]
Thanks @richardgill for quick update .. `text-xl` is probably only for me as I am creating custom fontSize classes ... I guess handling for custom classes would be out of scope for this library unless you are thinking of some way ...  In any case I would suggest to add a disclaimer
