### ISSUE TITLE
Cli is not compatible with the current node version.

### ISSUE THREAD

**Issue by stevica-canadi** [richardgill/tailwind-override#7]
Hello is it possible to update the node version in the package.json to at least 14.17.1 ?
Since when I try to add the cli it cannot be added to the project and I cannot use node @13 since other tailwind css dependencies wont work with it.

Thanks

yarn add tailwind-override-cli --dev
yarn add v1.22.10
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error tailwind-override-cli@0.0.7: The engine "node" is incompatible with this module. Expected version ">= 13.4 < 14". Got "14.17.1"
error Found incompatible module.

**Comment by richardgill** [comment]
Hi @stevica-canadi - apologies for the delay.

#8 fixes this. It's in npm as 0.0.10
